# Build-time git provenance for x7_efl_study (re-run on EVERY build,
# not at configure time — a configure-time value goes stale; review
# finding). Emits the FULL commit SHA and a dirty flag whose
# definition includes untracked files:
#   git status --porcelain=v1 --untracked-files=normal
# The file is rewritten only when its content changes, so an unchanged
# tree does not relink the study executable.
execute_process(
  COMMAND git -C "${SRC_DIR}" rev-parse HEAD
  OUTPUT_VARIABLE EFL_SHA
  OUTPUT_STRIP_TRAILING_WHITESPACE
  RESULT_VARIABLE EFL_SHA_RC)
execute_process(
  COMMAND git -C "${SRC_DIR}" status --porcelain=v1 --untracked-files=normal
  OUTPUT_VARIABLE EFL_STATUS
  RESULT_VARIABLE EFL_STATUS_RC)
if(NOT EFL_SHA_RC EQUAL 0)
  set(EFL_SHA "unknown")
endif()
if(EFL_STATUS_RC EQUAL 0 AND EFL_STATUS STREQUAL "")
  set(EFL_DIRTY "false")
else()
  set(EFL_DIRTY "true")
endif()
set(CONTENT "// generated by cmake/GitRev.cmake — do not edit
namespace x7::gitrev {
extern const char* const kBuildSha = \"${EFL_SHA}\";
extern const bool kBuildDirty = ${EFL_DIRTY};
}  // namespace x7::gitrev
")
if(EXISTS "${OUT}")
  file(READ "${OUT}" OLD)
else()
  set(OLD "")
endif()
if(NOT OLD STREQUAL CONTENT)
  file(WRITE "${OUT}" "${CONTENT}")
endif()
