// M-GC2 vendor MODEL parity against an INDEPENDENT fixture (review
// finding: the earlier parity checks used rtctrl's gravity model on
// both sides and could not detect the known model difference). The
// frozen table below was generated by the VENDOR's own gravity
// algorithm — their link CSV, their recursion, their hand-excluding
// route, their tuned torque-to-current constants — via
// tests/fixtures/vendor_gravity_dump.cpp (regeneration command in its
// header). This test detects and BOUNDS the model difference instead
// of assuming it away.
#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>

#include <cmath>

#include "rtctrl/hw/command_current.hpp"
#include "rtctrl/hw/config.hpp"
#include "rtctrl/model/chain_model.hpp"
#include "rtctrl/model/joint_map.hpp"
#include "rtctrl/model/zvector.hpp"

using Catch::Approx;
namespace hw = rtctrl::hw;
namespace model = rtctrl::model;
using model::kCanonicalDof;

namespace {

// Reference postures (canonical q8; the vendor computes 7 arm joints).
// Rows: upright zero; the EFL study's development pose; the 2026-07-28
// track-incident settle posture; the 2026-07-29 float-incident start.
constexpr int kPostures = 4;
constexpr double kQ8[kPostures][kCanonicalDof] = {
    {0, 0, 0, 0, 0, 0, 0, 0},
    {0.0, 0.2, 0.0, -0.4, 0.0, -0.2, 0.0, 0.1},
    {-0.10738, 0.50928, 0.19021, -1.87299, 0.02608, -0.79153, -0.05983,
     -0.01841},
    {-0.63353, -1.39285, 1.77942, -1.74260, -0.96487, -0.05676,
     -0.63200, -0.01227}};

// FROZEN vendor outputs [A] for arm joints 0..6 (generator output,
// 2026-07-30). The vendor computes NO gripper torque (its route ends
// before the hand links), so canonical joint 7 has no vendor column.
constexpr double kVendorCurrents[kPostures][7] = {
    {0.000000000, -0.015339728, 0.000000000, -0.005498940, 0.000000000,
     0.003862394, 0.000000000},
    {-0.000000000, -0.068585868, 0.000164013, 0.109262481, -0.000128429,
     0.011059562, -0.000217033},
    {-0.000000000, 0.011952963, -0.046320549, 0.539466670, -0.001723106,
     0.013811087, -0.000464987},
    {0.000000000, 0.547628653, 0.513961827, 0.115856406, 0.001183654,
     0.018119082, -0.000551021}};

// The vendor's tuned constants [Nm/A] (samples03).
constexpr double kVendorKt[7] = {2.20, 3.60, 2.20, 2.20, 2.20, 2.20,
                                 2.20};

// Preregistered model-difference envelope [Nm]: the measured maximum
// across all postures/joints is 0.089 (float posture, joint 2),
// attributed to the vendor's excluded ~30 g hand assembly and
// link-parameter differences.
constexpr double kModelEnvelopeNm = 0.10;

}  // namespace

TEST_CASE("rtctrl gravity matches the independent vendor fixture "
          "within the model envelope",
          "[hw][calibration][vendor]") {
  model::ChainModel chain("models/crane_x7/crane_x7.ztk");
  model::JointMap map(chain);
  const auto vendor_cfg =
      hw::Config::load("config/crane_x7_vendor_scale.toml");

  for (int p = 0; p < kPostures; ++p) {
    model::ZVector q8(kCanonicalDof), tau(kCanonicalDof);
    for (int i = 0; i < kCanonicalDof; ++i) q8[i] = kQ8[p][i];
    chain.gravityTorque(map, q8.get(), tau.get());
    for (int i = 0; i < 7; ++i) {
      // torque-domain model difference, bounded
      const double tau_vendor = kVendorCurrents[p][i] * kVendorKt[i];
      REQUIRE_THAT(
          tau[i], Catch::Matchers::WithinAbs(tau_vendor, kModelEnvelopeNm));
      // current-domain: our vendor-scaled command vs the vendor's own
      // current — the end-to-end posture-to-current comparison the
      // M-GC2 gate names (envelope / kt_vendor)
      const double i_ours =
          hw::commandCurrentFromTorque(vendor_cfg.joints[i], tau[i]);
      REQUIRE_THAT(i_ours,
                   Catch::Matchers::WithinAbs(kVendorCurrents[p][i],
                                              kModelEnvelopeNm / 2.20));
    }
  }
}

TEST_CASE("the model reproduces the float incident's logged request",
          "[hw][calibration][vendor]") {
  // float1.csv row 0 recorded tau_request1 = +2.0219 Nm at the float
  // start posture — the fixture's provenance tie to the incident log.
  model::ChainModel chain("models/crane_x7/crane_x7.ztk");
  model::JointMap map(chain);
  model::ZVector q8(kCanonicalDof), tau(kCanonicalDof);
  for (int i = 0; i < kCanonicalDof; ++i) q8[i] = kQ8[3][i];
  chain.gravityTorque(map, q8.get(), tau.get());
  REQUIRE(tau[1] == Approx(2.0219).margin(5e-4));
  // and the vendor model differs by the small MODEL delta, not the
  // large current delta: the incident's 0.839 A vs 0.548 A split is
  // ~2.5% model difference and ~49% torque-constant calibration
  REQUIRE(kVendorCurrents[3][1] * kVendorKt[1] ==
          Approx(1.9715).margin(5e-4));
}
